install:
	mkdir -p ~/.local/share/spotify-indicator
	cp ./spotify-indicator.py ~/.local/share/spotify-indicator
	cp ./Spotify_Icon_RGB_Green.png ~/.local/share/spotify-indicator
	cp ./Spotify_Icon_RGB_White.png ~/.local/share/spotify-indicator
	chmod +x ~/.local/share/spotify-indicator/spotify-indicator.py
	ln -sf ~/.local/share/spotify-indicator/spotify-indicator.py ~/.local/bin/spotify-indicator